
import type { CropDetails, CropId, GameState, Plot, MarketItem, SeedId } from '@/types';

export const GRID_ROWS = 3;
export const GRID_COLS = 5;
export const TOTAL_PLOTS = GRID_ROWS * GRID_COLS;

export const INITIAL_GOLD = 100;
export const INITIAL_XP = 0;
export const INITIAL_LEVEL = 1;

export const CROP_DATA: Record<CropId, CropDetails> = {
  tomato: {
    name: 'Cà Chua',
    seedName: 'tomatoSeed',
    icon: '🍅',
    timeToGrowing: 60 * 1000, 
    timeToReady: 120 * 1000,
    harvestYield: 3,
    seedPrice: 5,
    cropPrice: 2,
  },
  carrot: {
    name: 'Cà Rốt',
    seedName: 'carrotSeed',
    icon: '🥕',
    timeToGrowing: 120 * 1000, 
    timeToReady: 240 * 1000, 
    harvestYield: 2,
    seedPrice: 8,
    cropPrice: 5,
  },
  corn: {
    name: 'Ngô',
    seedName: 'cornSeed',
    icon: '🌽',
    timeToGrowing: 180 * 1000, 
    timeToReady: 360 * 1000,  
    harvestYield: 1,
    seedPrice: 12,
    cropPrice: 15,
  },
  strawberry: {
    name: 'Dâu Tây',
    seedName: 'strawberrySeed',
    icon: '🍓',
    timeToGrowing: 90000,
    timeToReady: 200000,
    harvestYield: 4,
    seedPrice: 10,
    cropPrice: 3,
  },
  blueberry: {
    name: 'Việt Quất',
    seedName: 'blueberrySeed',
    icon: '🫐',
    timeToGrowing: 100000,
    timeToReady: 220000,
    harvestYield: 5,
    seedPrice: 12,
    cropPrice: 3,
  },
  watermelon: {
    name: 'Dưa Hấu',
    seedName: 'watermelonSeed',
    icon: '🍉',
    timeToGrowing: 200000,
    timeToReady: 450000,
    harvestYield: 1,
    seedPrice: 25,
    cropPrice: 30,
  },
  pineapple: {
    name: 'Dứa (Thơm)',
    seedName: 'pineappleSeed',
    icon: '🍍',
    timeToGrowing: 250000,
    timeToReady: 500000,
    harvestYield: 1,
    seedPrice: 30,
    cropPrice: 35,
  },
  mango: {
    name: 'Xoài',
    seedName: 'mangoSeed',
    icon: '🥭',
    timeToGrowing: 180000,
    timeToReady: 400000,
    harvestYield: 2,
    seedPrice: 20,
    cropPrice: 12,
  },
  grapes: {
    name: 'Nho',
    seedName: 'grapesSeed',
    icon: '🍇',
    timeToGrowing: 150000,
    timeToReady: 300000,
    harvestYield: 10,
    seedPrice: 18,
    cropPrice: 2,
  },
  kiwi: {
    name: 'Kiwi',
    seedName: 'kiwiSeed',
    icon: '🥝',
    timeToGrowing: 130000,
    timeToReady: 280000,
    harvestYield: 3,
    seedPrice: 15,
    cropPrice: 6,
  },
  peach: {
    name: 'Đào',
    seedName: 'peachSeed',
    icon: '🍑',
    timeToGrowing: 160000,
    timeToReady: 320000,
    harvestYield: 2,
    seedPrice: 17,
    cropPrice: 10,
  },
  cherry: {
    name: 'Anh Đào',
    seedName: 'cherrySeed',
    icon: '🍒',
    timeToGrowing: 110000,
    timeToReady: 250000,
    harvestYield: 8,
    seedPrice: 22,
    cropPrice: 3,
  },
  lemon: {
    name: 'Chanh Vàng',
    seedName: 'lemonSeed',
    icon: '🍋',
    timeToGrowing: 100000,
    timeToReady: 230000,
    harvestYield: 4,
    seedPrice: 9,
    cropPrice: 3,
  },
  orange: {
    name: 'Cam',
    seedName: 'orangeSeed',
    icon: '🍊',
    timeToGrowing: 170000,
    timeToReady: 350000,
    harvestYield: 3,
    seedPrice: 16,
    cropPrice: 7,
  },
  apple: {
    name: 'Táo Đỏ',
    seedName: 'appleSeed',
    icon: '🍎',
    timeToGrowing: 140000,
    timeToReady: 290000,
    harvestYield: 2,
    seedPrice: 14,
    cropPrice: 8,
  },
  greenapple: {
    name: 'Táo Xanh',
    seedName: 'greenappleSeed',
    icon: '🍏',
    timeToGrowing: 145000,
    timeToReady: 300000,
    harvestYield: 2,
    seedPrice: 15,
    cropPrice: 8,
  },
  pear: {
    name: 'Lê',
    seedName: 'pearSeed',
    icon: '🍐',
    timeToGrowing: 155000,
    timeToReady: 310000,
    harvestYield: 2,
    seedPrice: 16,
    cropPrice: 9,
  },
  banana: {
    name: 'Chuối',
    seedName: 'bananaSeed',
    icon: '🍌',
    timeToGrowing: 125000,
    timeToReady: 260000,
    harvestYield: 5,
    seedPrice: 13,
    cropPrice: 3,
  },
  avocado: {
    name: 'Bơ',
    seedName: 'avocadoSeed',
    icon: '🥑',
    timeToGrowing: 220000,
    timeToReady: 480000,
    harvestYield: 2,
    seedPrice: 28,
    cropPrice: 18,
  },
  eggplant: {
    name: 'Cà Tím',
    seedName: 'eggplantSeed',
    icon: '🍆',
    timeToGrowing: 135000,
    timeToReady: 270000,
    harvestYield: 3,
    seedPrice: 11,
    cropPrice: 4,
  },
  potato: {
    name: 'Khoai Tây',
    seedName: 'potatoSeed',
    icon: '🥔',
    timeToGrowing: 115000,
    timeToReady: 240000,
    harvestYield: 4,
    seedPrice: 7,
    cropPrice: 2,
  },
  onion: {
    name: 'Hành Tây',
    seedName: 'onionSeed',
    icon: '🧅',
    timeToGrowing: 95000,
    timeToReady: 200000,
    harvestYield: 3,
    seedPrice: 6,
    cropPrice: 2,
  },
  garlic: {
    name: 'Tỏi',
    seedName: 'garlicSeed',
    icon: '🧄',
    timeToGrowing: 85000,
    timeToReady: 190000,
    harvestYield: 5,
    seedPrice: 8,
    cropPrice: 2,
  },
  broccoli: {
    name: 'Bông Cải Xanh',
    seedName: 'broccoliSeed',
    icon: '🥦',
    timeToGrowing: 105000,
    timeToReady: 220000,
    harvestYield: 1,
    seedPrice: 10,
    cropPrice: 12,
  },
  bellpepper: {
    name: 'Ớt Chuông',
    seedName: 'bellpepperSeed',
    icon: '🫑',
    timeToGrowing: 125000,
    timeToReady: 260000,
    harvestYield: 3,
    seedPrice: 13,
    cropPrice: 5,
  },
  cucumber: {
    name: 'Dưa Chuột',
    seedName: 'cucumberSeed',
    icon: '🥒',
    timeToGrowing: 75000,
    timeToReady: 180000,
    harvestYield: 2,
    seedPrice: 5,
    cropPrice: 3,
  },
  lettuce: {
    name: 'Xà Lách',
    seedName: 'lettuceSeed',
    icon: '🥬',
    timeToGrowing: 65000,
    timeToReady: 150000,
    harvestYield: 1,
    seedPrice: 4,
    cropPrice: 5,
  },
  mushroom: {
    name: 'Nấm',
    seedName: 'mushroomSeed',
    icon: '🍄',
    timeToGrowing: 55000,
    timeToReady: 120000,
    harvestYield: 6,
    seedPrice: 15,
    cropPrice: 3,
  },
  peanut: {
    name: 'Đậu Phộng',
    seedName: 'peanutSeed',
    icon: '🥜',
    timeToGrowing: 145000,
    timeToReady: 300000,
    harvestYield: 10,
    seedPrice: 12,
    cropPrice: 1,
  },
  chestnut: {
    name: 'Hạt Dẻ',
    seedName: 'chestnutSeed',
    icon: '🌰',
    timeToGrowing: 280000,
    timeToReady: 550000,
    harvestYield: 2,
    seedPrice: 35,
    cropPrice: 20,
  },
  coconut: {
    name: 'Dừa',
    seedName: 'coconutSeed',
    icon: '🥥',
    timeToGrowing: 300000,
    timeToReady: 600000,
    harvestYield: 1,
    seedPrice: 40,
    cropPrice: 45,
  },
  sweetpotato: {
    name: 'Khoai Lang',
    seedName: 'sweetpotatoSeed',
    icon: '🍠',
    timeToGrowing: 130000,
    timeToReady: 280000,
    harvestYield: 3,
    seedPrice: 9,
    cropPrice: 4,
  },
  chilipepper: {
    name: 'Ớt Cay',
    seedName: 'chilipepperSeed',
    icon: '🌶️',
    timeToGrowing: 100000,
    timeToReady: 210000,
    harvestYield: 8,
    seedPrice: 11,
    cropPrice: 2,
  },
  rice: {
    name: 'Lúa Gạo',
    seedName: 'riceSeed',
    icon: '🌾',
    timeToGrowing: 200000,
    timeToReady: 420000,
    harvestYield: 15,
    seedPrice: 10,
    cropPrice: 1,
  },
  sugarcane: {
    name: 'Mía',
    seedName: 'sugarcaneSeed',
    icon: '🎋', // Placeholder, actual sugarcane might not have specific emoji
    timeToGrowing: 190000,
    timeToReady: 380000,
    harvestYield: 3,
    seedPrice: 14,
    cropPrice: 6,
  },
  cabbage: {
    name: 'Bắp Cải',
    seedName: 'cabbageSeed',
    icon: '🥬', // Shared with lettuce
    timeToGrowing: 110000,
    timeToReady: 230000,
    harvestYield: 1,
    seedPrice: 7,
    cropPrice: 8,
  },
  radish: {
    name: 'Củ Cải',
    seedName: 'radishSeed',
    icon: '⚪', // Placeholder: white circle
    timeToGrowing: 70000,
    timeToReady: 160000,
    harvestYield: 3,
    seedPrice: 6,
    cropPrice: 3,
  },
  cauliflower: {
    name: 'Súp Lơ Trắng',
    seedName: 'cauliflowerSeed',
    icon: '🥦', // Shared with broccoli
    timeToGrowing: 115000,
    timeToReady: 240000,
    harvestYield: 1,
    seedPrice: 11,
    cropPrice: 13,
  },
  olive: {
    name: 'Ô Liu',
    seedName: 'oliveSeed',
    icon: '🫒',
    timeToGrowing: 240000,
    timeToReady: 490000,
    harvestYield: 6,
    seedPrice: 26,
    cropPrice: 5,
  },
  papaya: {
    name: 'Đu Đủ',
    seedName: 'papayaSeed',
    icon: '🥭', // Shared with mango
    timeToGrowing: 175000,
    timeToReady: 360000,
    harvestYield: 2,
    seedPrice: 19,
    cropPrice: 11,
  },
  plum: {
    name: 'Mận',
    seedName: 'plumSeed',
    icon: '🍑', // Shared with peach
    timeToGrowing: 165000,
    timeToReady: 330000,
    harvestYield: 4,
    seedPrice: 18,
    cropPrice: 5,
  },
  zucchini: {
    name: 'Bí Ngòi',
    seedName: 'zucchiniSeed',
    icon: '🥒', // Shared with cucumber
    timeToGrowing: 80000,
    timeToReady: 170000,
    harvestYield: 2,
    seedPrice: 7,
    cropPrice: 4,
  },
  pumpkin: {
    name: 'Bí Ngô',
    seedName: 'pumpkinSeed',
    icon: '🎃',
    timeToGrowing: 220000,
    timeToReady: 470000,
    harvestYield: 1,
    seedPrice: 20,
    cropPrice: 25,
  },
  spinach: {
    name: 'Rau Bina',
    seedName: 'spinachSeed',
    icon: '🥬', // Shared
    timeToGrowing: 50000,
    timeToReady: 110000,
    harvestYield: 2,
    seedPrice: 3,
    cropPrice: 2,
  },
  artichoke: {
    name: 'Atiso',
    seedName: 'artichokeSeed',
    icon: '🌸', // Placeholder: Cherry Blossom as no direct emoji
    timeToGrowing: 190000,
    timeToReady: 390000,
    harvestYield: 1,
    seedPrice: 22,
    cropPrice: 25,
  },
  asparagus: {
    name: 'Măng Tây',
    seedName: 'asparagusSeed',
    icon: '🌿', // Placeholder: Herb
    timeToGrowing: 100000,
    timeToReady: 220000,
    harvestYield: 4,
    seedPrice: 15,
    cropPrice: 4,
  },
  beetroot: {
    name: 'Củ Dền',
    seedName: 'beetrootSeed',
    icon: '🔴', // Placeholder: Red Circle
    timeToGrowing: 90000,
    timeToReady: 200000,
    harvestYield: 2,
    seedPrice: 8,
    cropPrice: 5,
  },
  celery: {
    name: 'Cần Tây',
    seedName: 'celerySeed',
    icon: '🥬', // Shared
    timeToGrowing: 70000,
    timeToReady: 150000,
    harvestYield: 1,
    seedPrice: 5,
    cropPrice: 6,
  },
  ginger: {
    name: 'Gừng',
    seedName: 'gingerSeed',
    icon: '🌾', // Placeholder: Sheaf of Rice (looks somewhat like ginger root)
    timeToGrowing: 120000,
    timeToReady: 250000,
    harvestYield: 3,
    seedPrice: 13,
    cropPrice: 5,
  },
  leek: {
    name: 'Tỏi Tây (Boa-rô)',
    seedName: 'leekSeed',
    icon: '🧅', // Shared
    timeToGrowing: 85000,
    timeToReady: 180000,
    harvestYield: 2,
    seedPrice: 7,
    cropPrice: 4,
  },
  peas: {
    name: 'Đậu Hà Lan',
    seedName: 'peasSeed',
    icon: '🟢', // Placeholder: Green Circle
    timeToGrowing: 60000,
    timeToReady: 130000,
    harvestYield: 10,
    seedPrice: 9,
    cropPrice: 1,
  },
  turnip: {
    name: 'Củ Cải Turnip',
    seedName: 'turnipSeed',
    icon: '🟣', // Placeholder: Purple Circle
    timeToGrowing: 75000,
    timeToReady: 160000,
    harvestYield: 2,
    seedPrice: 6,
    cropPrice: 4,
  },
  soybean: {
    name: 'Đậu Nành',
    seedName: 'soybeanSeed',
    icon: '🌱', // Seedling
    timeToGrowing: 140000,
    timeToReady: 300000,
    harvestYield: 8,
    seedPrice: 10,
    cropPrice: 2,
  },
  lentil: {
    name: 'Đậu Lăng',
    seedName: 'lentilSeed',
    icon: '🟤', // Brown Circle
    timeToGrowing: 130000,
    timeToReady: 280000,
    harvestYield: 12,
    seedPrice: 11,
    cropPrice: 1,
  }
};

export const ALL_CROP_IDS = Object.keys(CROP_DATA) as CropId[];
export const ALL_SEED_IDS = ALL_CROP_IDS.map(cropId => CROP_DATA[cropId].seedName as SeedId);


export const INITIAL_PLOTS: Plot[] = Array.from({ length: TOTAL_PLOTS }, (_, i) => ({
  id: i,
  state: 'empty',
}));

export const INITIAL_INVENTORY: GameState['inventory'] = {
  tomatoSeed: 5,
  carrotSeed: 3,
  cornSeed: 0,
  tomato: 0,
  carrot: 0,
  corn: 0,
  // Initialize new seeds to 0 or a small amount if desired
  strawberrySeed: 2, blueberrySeed: 0, watermelonSeed: 0, pineappleSeed: 0, mangoSeed: 0, grapesSeed: 0, kiwiSeed: 0, peachSeed: 0, cherrySeed: 0, lemonSeed: 0, orangeSeed: 0, appleSeed: 0, greenappleSeed: 0, pearSeed: 0, bananaSeed: 0, avocadoSeed: 0, eggplantSeed: 0, potatoSeed: 0, onionSeed: 0, garlicSeed: 0, broccoliSeed: 0, bellpepperSeed: 0, cucumberSeed: 0, lettuceSeed: 0, mushroomSeed: 0, peanutSeed: 0, chestnutSeed: 0, coconutSeed: 0, sweetpotatoSeed: 0, chilipepperSeed: 0, riceSeed: 0, sugarcaneSeed: 0, cabbageSeed: 0, radishSeed: 0, cauliflowerSeed: 0, oliveSeed: 0, papayaSeed: 0, plumSeed: 0, zucchiniSeed: 0, pumpkinSeed: 0, spinachSeed: 0, artichokeSeed: 0, asparagusSeed: 0, beetrootSeed: 0, celerySeed: 0, gingerSeed: 0, leekSeed: 0, peasSeed: 0, turnipSeed: 0, soybeanSeed: 0, lentilSeed: 0,
  // Initialize new crops to 0
  strawberry: 0, blueberry: 0, watermelon: 0, pineapple: 0, mango: 0, grapes: 0, kiwi: 0, peach: 0, cherry: 0, lemon: 0, orange: 0, apple: 0, greenapple: 0, pear: 0, banana: 0, avocado: 0, eggplant: 0, potato: 0, onion: 0, garlic: 0, broccoli: 0, bellpepper: 0, cucumber: 0, lettuce: 0, mushroom: 0, peanut: 0, chestnut: 0, coconut: 0, sweetpotato: 0, chilipepper: 0, rice: 0, sugarcane: 0, cabbage: 0, radish: 0, cauliflower: 0, olive: 0, papaya: 0, plum: 0, zucchini: 0, pumpkin: 0, spinach: 0, artichoke: 0, asparagus: 0, beetroot: 0, celery: 0, ginger: 0, leek: 0, peas: 0, turnip: 0, soybean: 0, lentil: 0,
};

export const INITIAL_GAME_STATE: GameState = {
  gold: INITIAL_GOLD,
  xp: INITIAL_XP,
  level: INITIAL_LEVEL,
  plots: INITIAL_PLOTS,
  inventory: INITIAL_INVENTORY,
  lastUpdate: Date.now(),
};

export const LEVEL_UP_XP_THRESHOLD = (level: number): number => {
  return Math.floor(100 * Math.pow(level, 1.5)); // Làm tròn xuống để đảm bảo là số nguyên
};

export const MARKET_ITEMS: MarketItem[] = [
  ...ALL_CROP_IDS.map(cropId => ({
    id: CROP_DATA[cropId].seedName as SeedId,
    name: `${CROP_DATA[cropId].name} (Hạt Giống)`,
    price: CROP_DATA[cropId].seedPrice,
    type: 'seed' as 'seed'
  })),
  ...ALL_CROP_IDS.map(cropId => ({
    id: cropId,
    name: CROP_DATA[cropId].name,
    price: CROP_DATA[cropId].cropPrice,
    type: 'crop' as 'crop'
  })),
];

export const LOCAL_STORAGE_GAME_KEY = 'happyFarmGame';

